name: shenfun_doc_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  - cython
  - fftw
  - numpy
  - sympy
  - scipy
  - mpi4py
  - mpi4py-fft
  - Sphinx==2.2.*
  - nbsphinx
  - pip:
    - sphinxcontrib-bibtex<2.0.0
